### ISSUE TITLE
Decide what to do with "client-side generation" in Introduction - figure 1.1

### ISSUE THREAD

**Issue by unode** [carpentries-incubator/jekyll-pages-novice#105]
#### Static vs dynamic

The text explains two types but Figure 1.1 shows a third panel - "client-side generation" - that isn't mentioned.

I think we should replace this image or:

1. move the client-side to be in-between static and dynamic and add an image overlay (red line, contour box, etc) marking both "dynamic server-side" and "client-side" as "dynamic"
2. omit "client-side" entirely.

I'm inclined to 2. since "client-side" can be quite a broad gradient between static and dynamic and I don't think we need to get into that here.

**Comment by tobyhodges** [comment]
I think we could "just" crop the right-hand-side out of the SVG and re-center the text labels. Then we would need to adjust the caption to state that the image is adapted from the one originally used in JS4DS.

I tried to take care of this myself but have been having trouble with my SVG editor. Anyone else want to take a stab at this?

**Comment by unode** [comment]
I'm happy to have a go at it.

**Comment by unode** [comment]
I tried with Inkscape and also got glitchy behaviour all over the place.
Seems like this SVG contains invalid markup that makes Inkscape unhappy.
Regardless, I managed to blindly edit the file and push it in #190

**Comment by tobyhodges** [comment]
Closed via #190
