### ISSUE TITLE
Correct solution for exercise "Perfect tool for the job" in Introduction

### ISSUE THREAD

**Issue by unode** [carpentries-incubator/jekyll-pages-novice#106]
##### Perfect tool for the job

The exercise description and the solution are out-of-sync.
There are now 6 options but only 5 are mentioned in the solution.

**Comment by tobyhodges** [comment]
This is a result of the markdown list being rendered with different numbering than you wrote in the source file - probably best to restructure the solution block to avoid this problem.

**Comment by annefou** [comment]
Maybe having a sub-title for each sub-question/solution such as:
- **personal website**: 
- **forum/discussion**:
- **blog/news**:
- **search engine**:
- **wiki**:
- **online book**:

**Comment by tobyhodges** [comment]
Looks like this was fixed
