### ISSUE TITLE
Add Extra about CodiMD

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/jekyll-pages-novice#110]
@annefou and I are going to use CodiMD for note-taking etc during the trial run next week, and (inspired by Code Refinery's [_HackMD Mechanics_](https://coderefinery.github.io/manuals/hackmd-mechanics/#basic-controls)) guide, we think it would be good to add an Extra about using CodiMD. This will probably help other instructors preparing to teach this lesson in their own workshops, and makes more sense as an Extra than a section in the Instructors' Notes because it will probably be fairly long...

**Comment by tobyhodges** [comment]
FYI CodiMD is now called [HedgeDoc](https://hedgedoc.org/history/)

**Comment by tobyhodges** [comment]
Add to Instructor Notes (`_extras/guide.md`), alongside a recommendation for instructors to use CodiMD for their workshops

**Comment by unode** [comment]
A minor compatibility note. We already have a callout on soft vs hard line breaks but...
CodiMD doesn't distinguish soft from hard line breaks by default. Jekyll does, which may cause formatting differences.
The Carpentries CodiMD doesn't distinguish either - compare [default line breaks](https://codimd.carpentries.org/test?both) with [the jekyll way - aka only hard line breaks](https://codimd.carpentries.org/test-2?both).

We may need to ask The Carpentries to set `CMD_DEFAULT_USE_HARD_BREAK = true` ([reference here](https://hackmd.io/s/codimd-configuration#User-Features)) to have consistent behaviour with Jekyll/GitHub markdown.

**Comment by tobyhodges** [comment]
I can see how making the behaviour consistent between the CodiMD and Jekyll could be useful, but I also see how, for the its primary purpose of collaborative editing, keeping the current default for CodiMD could be helpful. (Think of the use case where you have ten people all writing simultaneously on successive lines...) I think I might prefer to keep the default as-is and add a note to the Extra content on CodiMD about making sure to add `breaks: false` to the header of the notes doc for the lesson.
