### ISSUE TITLE
review episode "Hosting websites on Github"

### ISSUE THREAD

**Issue by annefou** [carpentries-incubator/jekyll-pages-novice#114]
**Scroll down to “GitHub Pages” settings. You will see that these are currently disabled. Select branch main to enable GitHub Pages for this repository and to tell GitHub which branch to use as a source.**

We forgot to tell our learners to click on the "save" button (otherwise the link does not appear). Also we need that they may have to "refresh" their webpage.

**Comment by annefou** [comment]
**Exercise: Add New Content to the Website**: in the solution, we show 
```
# My Research Project

## Description
This research project is all about teaching you how to create websites with GitHub pages.

```

But above, we showed:

```
# group-website

```

To solve this inconsistency, I suggest we show `# My Research Project` instead of  `# group-website`.

In addition, I would add more information on what to write. For instance move the section:

```
Edit index.md file to look something like:

# My Research Project

## Description
This research project is all about teaching you how to create websites with GitHub pages.

```

From the solution to the question.

**Comment by annefou** [comment]
**Exercise: Create Links Between Pages**: 

- I don't think learners can make this exercise without more guidance on the content to add in about.md. (same comment as above). I would move some of the information given in the solution to the question/exercise content.

- I was initially confused because the link was broken: we need to remind learners (and instructors!) that it can take a few minutes before the website is re-rendered (check "green" tick when rebuild is done).

- Adding links following what is suggested does not work for me. I had to change:

```

More details about the project are available from the [About page](/about).
```

to:

```
More details about the project are available from the [About page](about.md).
```

**Comment by tobyhodges** [comment]
> `More details about the project are available from the [About page](about.md).`

I used `[About page](about)` and that worked fine. 

A note to all contributors (pinging @sstevens2 @JulianKarlBauer @unode and @anenadic): when writing internal link targets as absolute paths, **there are often differences between the valid path in a local build and the valid path in a site served via GitHub Pages**. This is because the local site is served from the root of your localhost, whereas Github Pages sites are served from `/<your-repo-name>`. 

The safest thing to do when writing internal links is to use the `relative_root_path` variable from `_includes/base_path.html`, which provides the site root regardless of whether the site is being viewed locally or via Github Pages.

**Comment by tobyhodges** [comment]
I've hotfixed that link target in `github-pages.md`

**Comment by tobyhodges** [comment]
> In addition, I would add more information on what to write.

We should agree on how rigidly we want learners to follow what we're writing in these files. I agree with @annefou that the safest approach would be to define exactly what content we want them to add to the files as we work through the lesson. That said, most of the text is customisable according to their preference, as long as they observe the structural/functional elements of the content we're introducing. 

We _could_ add a note saying something like

> We suggest adding the text below, but feel free to replace this text with something else in your page if you prefer.

I am pretty much on the fence about this. What do others think?

**Comment by sstevens2** [comment]
I agree with the text they can freestyle a bit or type the same thing we do.  The key might be to point out when syntax is important, because it will change the way something renders, and when they can decide what to put in their example site.

**Comment by unode** [comment]
> The safest thing to do when writing internal links is to use the `relative_root_path` variable from `_includes/base_path.html`, which provides the site root regardless of whether the site is being viewed locally or via Github Pages.

Grabbing from #99 , would it make sense to turn this into an exercise? It's a bit of a gotcha where `relative_root_path` is the only correct answer. The `/` path works when previewing the markdown in GitHub though, so this can be quite confusing to learners.

**Comment by unode** [comment]
> I am pretty much on the fence about this. What do others think?

Giving too much freedom can make screenshots later on confusing if they assume the learner followed everything to the line.
I suggest we keep the main instructions rigid and the exercises flexible. We should then also be careful about not using output from exercises in subsequent screenshots.

Regardless, I think we should encourage tinkering during exercises. If they run into unexpected results that will likely lead to questions that will help the learning process.

**Comment by tobyhodges** [comment]
> would it make sense to turn this into an exercise? It's a bit of a gotcha where relative_root_path is the only correct answer.

Yes, maybe. But the code in `base_path.html` is not the easiest to understand. If you'd like to have a go at putting the exercise together, @unode, I'll be happy to review it.
