### ISSUE TITLE
review "Re-using Blocks of Content"

### ISSUE THREAD

**Issue by annefou** [carpentries-incubator/jekyll-pages-novice#115]
For the banner, we suggest to add an image:

```
<img src="/images/site_banner.png" alt="Group Website with Jekyll">
```

1. For me it does not work: i need to change `/images/site_banner.png` by `images/site_banner.png`
2. Why using HTML notation for adding an image and not markdown? such as:

```
![alt "Group Website with Jekyll"](images/site_banner.png)
```

**Comment by annefou** [comment]
Same comment for **Optional Exercise**. I would suggest to use markdown notation for links rather than HTML `<a>` and `</a>` i.e.:

```
[![alt "Group Website with Jekyll"](images/site_banner.png)](index.md)
```

Or we can add an aboslute link to the website:

```
[![alt "Group Website with Jekyll"](images/site_banner.png)](https://annefou.github.io/group-website/)
```

**Comment by annefou** [comment]
Later too. I am not sure why we chose to switch to HTML at this stage and not only use markdown.

For instance, create `_includes/banner.md` and then add `{% include banner.md %}` in all markdown files.

**Comment by annefou** [comment]
**Including Contact Information**

`Copy the snippet and save it into an appropriately-named file, then use an include statement to re-insert it at the bottom of your site’s index.md, and add it at the bottom of the team.md pages.`

- `team.md` does not exist. I guess we mean `about.md`

**Comment by annefou** [comment]
**Including Link References**

- link is broken: In the Authoring with Markdown section, we learned about...  We have
```
 [Authoring with Markdown](/markdown/) 
```

which does not work.

**Comment by tobyhodges** [comment]
> Why using HTML notation for adding an image and not markdown?

Yes let's go with Markdown syntax here. I'll submit a PR to fix this today.

> I would suggest to use markdown notation for links rather than HTML `<a>` and `</a>`

Again, this is fine for me - this part will be confusing regardless of whether we use HTML or Markdown! And is probably less confusing with Markdown...

> I am not sure why we chose to switch to HTML at this stage and not only use markdown.

It made sense in my brain at the time 😆 but I agree.

> team.md does not exist. I guess we mean about.md

Good catch, @annefou! This is a hangover from when we were building a Team Members page in the GH Pages episode. That part has now been moved to the `arrays` episode coming later.

> link is broken

again hitting the problem with local vs online paths I mentioned in #114...

PR incoming to fix all of these.

**Comment by tobyhodges** [comment]
> It made sense in my brain at the time 😆 but I agree.

Working through this again, I remember that the problem is one cannot include Markdown in a layout file, so anything written as Markdown in this episode will need to be converted to HTML in the next. Do you think it's better to start with HTML here, or change it when adding these blocks to the layouts?

**Comment by annefou** [comment]
Close this issue (we would re-open if necessary!).
