### ISSUE TITLE
Review "Page Layouts"

### ISSUE THREAD

**Issue by annefou** [carpentries-incubator/jekyll-pages-novice#116]
- A screenshot is missing. Search for `FIXME: add screenshot here`

**Comment by annefou** [comment]
I am not sure why we do not use banner.html to generate `_layouts/page.html` (as we do for contacts). In addition, I am not sure why we removed the links  i.e.:

```
<a href="https://YOUR_USERNAME.github.io/YOUR_REPO_NAME/"><img src="images/site_banner.png" alt="Group Website with Jekyll"></a>
```


I would create `_layouts/page.html` with:

```
  
{% include banner.html %} 

{{ content }}

```

**Comment by annefou** [comment]
**Expanding the layout**

- In `_layouts/page.html` adding `{% include contact.md %}` did not work for me. I had to switch to HTML i.e. changed the content of `contact.md` to:

```
Have any questions about what we do?  <a href="mailto:{{site.email}}">We'd love to hear from you!</a>
```
and renamed `contact.md` to `contact.html`.


and now I have in `_layouts/page.html`:

```
  
{% include banner.html %} 

{{ content }}

{% include contact.html %}
```

**Comment by annefou** [comment]
- Typo to fix: `different diplays/devices,` to be changed to **different displays/devices,**.

*Exercise*:  **Laying the groundwork** is not correct and confusing. Here is what I did:

- First I used the following `default.html`:

```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
  </head>
  <body>
    {% include banner.html %}
    <h1>{{ title }}</h1>
    <section>
      {{ content }}
    </section>
    <footer>
      An example website made with Jekyll.
    </footer>
  </body>
</html>
```

i.e. not `page.title` but `title` (as for content).

- Changed `layout: page ` to `layout: default` in `index.md` default.html` for instance in `index.md ` or `about.md` (instead of using `page.html` layout)?

- then create a new `_includes/footer.html` with footer information (removed from default.html) and then include it in `default.html`

`default.html`:

```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
  </head>
  <body>
    {% include banner.html %}
    <h1>{{ title }}</h1>
    <section>
      {{ content }}
    </section>
    {% include footer.html %}
  </body>
</html>
```

`footer.html`:

```
    <footer>
      An example website made with Jekyll.
    </footer>
```

**Comment by annefou** [comment]
**Layout inheritance**:

```
---
layout: default
---

{{ content }}

{% include contact.html %}

```

(and not contact.md). And then we can see it in `about.md`

- we can also change the layout from `default` to `page` in  `index.md`.

**Comment by tobyhodges** [comment]
> I am not sure why we do not use banner.html to generate _layouts/page.html (as we do for contacts). In addition, I am not sure why we removed the links [...]

This is definitely the better approach as we are writing the banner image block in Markdown now. I will update.

**Comment by annefou** [comment]
Close for now and we can open a new issue if necessary.
