### ISSUE TITLE
Write learner profiles

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/jekyll-pages-novice#12]
the lesson needs some learner profiles, to describe its target audience. These should go into a new file at `files/audience.md`.

**Comment by sstevens2** [comment]
- Person who knows Git already - **Toby**
- Creating a research project/lab website to store documentation and track issues and collaborate with a team - **Toby**
- Creating a personal website or a publicly visible CV page - **Toby**
- Carpentries instructor to create workshop websites, not much or no Git - **Sarah**
- Developer who wants to create documentation pages for their software/project
- Someone looking for a free web hosting platform, little or limited HTML knowledge

**Comment by sstevens2** [comment]
> Anita is a new Carpentries instructor.  
> She is a librarian for the biology library at her institution.  
> She learned to work with HTML when she did her masters in library science.
> Since grad school, she has been picking up other coding skills and has recently learned R. 
> The Carpentries instructor who taught her R encouraged her to take Carpentries Instructor Training.
> She's never used git before but wants to help edit the Carpentries lessons and create new lessons 
> on topics she thinks would be useful for the students and staff she works with.  
> After working through this lesson Anita will be comfortable using Github to modify the Carpentries lessons, 
> playing with her own jekyll pages repo, and eventually making her own lessons using the Carpentries Lesson template.

Let me know if there is more detail I should add to this learner profile.

**Comment by tobyhodges** [comment]
> Let me know if there is more detail I should add to this learner profile.

This is great! It provides enough detail of background and motivation, and the persona is believable. The only thing I think it's missing is a final sentence about why the lesson is a good fit for Anita. I always like to finish the learner profiles with a sentence starting "After following this lesson, [X] will ..." or "Following this lesson will help [Y] ..." and I think something like that would help here.

**Comment by sstevens2** [comment]
Thanks @tobyhodges!  I like the addition of learning objectives at the end like that.  I've drafted a few and added them to my previous comment. Feedback appreciated!

**Comment by tobyhodges** [comment]
Yes, I think that's really helped! Thanks Sarah.

**Comment by tobyhodges** [comment]
> Arjun is a third-year PhD student studying atmospheric chemistry.
> He uses Python in his research every day and keeps all his scripts and files under version control with Git.
> His supervisor is a new group leader and Arjun was the first PhD student she recruited.
> Now that her lab has begun to publish the results of their research,
> she's tasked Arjun with setting up a website for the group.
> The time and budget the group has for developing and maintaining the site are limited,
> and Arjun wants to make sure his labmates can access and edit the pages.
> He's seen some other labs use GitHub Pages to host their websites
> and thinks this is a good opportunity to put his Git skills to work.
> After following this lesson, Arjun will be able to create and maintain the structure of the lab website through GitHub Pages, and begin teaching his colleagues how to collaborate on the content.

This one might hit both the "Person who knows Git already" and "Person building research group pages" points?

**Comment by tobyhodges** [comment]
and one more...

> An is in the final months of her Masters program in Digital Humanities.
> During her six-month lab internship, she started using a couple of tools available on GitHub, and became familiar with the interface. 
> She's really enjoyed this part of the internship and other technical aspects of her Masters and now wants to find work in digitization of rare books and other written material.
> She wants to increase her online profile as she enters the job market, and she knows that a personal website and online CV are a good place to start with this.
> An still needs to finish writing her thesis and doesn't have a lot of time to spare for creating a website from scratch, nor a lot of money to pay for hosting, domain names, and so on.
> This lesson will teach An how to find and use an existing template to create her personal webpage and online CV, how to write formatted text and insert images to highlight the skills she's picked up, and how to host those pages online for free.

**Comment by tobyhodges** [comment]
Closing this now via #33, as I think the three we have is enough
