### ISSUE TITLE
Suggestion for markdown restructuring

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/jekyll-pages-novice#121]
[In the Nov 11 pilot](https://codimd.carpentries.org/KyHEeesgS7mXKjwwvmHcrw) we came to the conclusion that the markdown section needs to be shortened.  Our major recommendation is that we teach a couple of important features of markdown, headings and links for example, and then give them a good cheat sheet and have them do an exercise where they try out a few different markdown formatting features.  This would mean cutting down the exercises considerably too.

@annefou @tobyhodges and I agreed on this after the workshop but would like to hear from others.

cc: @anenadic @unode @JulianKarlBauer

**Comment by unode** [comment]
Sounds good to me. Do we also assume or require that they have a reasonable familiarity with HTML?

...or at least what you can do with it?

**Comment by annefou** [comment]
I think the HTML section we have in the introduction was fine i.e. right length and sufficient to show that it is cumbersome to write HTML directly that's why creating website with markdown can really help.
