### ISSUE TITLE
Other markdown small changes

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/jekyll-pages-novice#122]
If we don't decide to restructure based on #121, here are some other issues we found in the [Nov 11 pilot notes](https://codimd.carpentries.org/KyHEeesgS7mXKjwwvmHcrw)

- Specify the level of headers are in the first Markdown exercise (if we keep the exercises)
- Add more clarification of how to break lines/paragraphs in markdown
- Explain that graphical preview is really a diff (without using the word diff) and will still show deleted lines (but highlighted red) so doesn't represent exactly what you will see after committing
- Update syntax highlighting screenshot to look like what the learners will see, it shows the rendered version of webpage that includes purple boxes.  Also in #113 
- Give them the code to copy for the syntax highlighting exercise so they don't have to type it all up
- Add in episode text which says that reference-style links help to reduce repeated effort in site maintenance. another (the first) example of good practice in Jekyll following the Don't Repeat Yourself principle.
- Add in episode text and an example about how to create a reference style link before the relevant exercise (if we week the exercises)

**Comment by tobyhodges** [comment]
This is still relevant - to the new Extras page about Markdown - so I am leaving this open for now.
