### ISSUE TITLE
Markdown lists render differently 

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/jekyll-pages-novice#125]
In the Jekyll lesson - Markdown lists render differently in the gh-pages we are creating and lesson pages we wrote these on. See the part introducing `_config.yml` for an example.  Might be hard to solve but suggestions welcome!

[From Nov 11 pilot notes](https://codimd.carpentries.org/KyHEeesgS7mXKjwwvmHcrw)

**Comment by unode** [comment]
See #128 if I got this one right.
