### ISSUE TITLE
Description of the contents of the lesson repository - for demo purposes

### ISSUE THREAD

**Issue by unode** [carpentries-incubator/jekyll-pages-novice#140]
Work in progress at: https://hackmd.io/YpeYnJBJRQST3gzhF_g_nQ

**Comment by tobyhodges** [comment]
pinging @anenadic

**Comment by tobyhodges** [comment]
I think this is almost ready to go. There is one comment outstanding on the document, about FAIR principles. Can you address/respond @unode?
