### ISSUE TITLE
Write Glossary?

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/jekyll-pages-novice#143]
As well as an aggregation of the key points for each episode, the Reference Extra page can also include a glossary of key terms described in the lesson. Right now that section of the page is a FIXME placeholder.

Now that [Glosario](https://glosario.carpentries.org/) exists, I think I'd prefer to add any relevant definitions there and link out from the episode pages every time a new term is introduced in the lesson. We could then adjust the title of the Reference page, to Reference rather than Glossary. What do others think?

**Comment by sstevens2** [comment]
From 2020-11-25 pilot, maybe we should at least include the jargon busting from here

```
Version control - software that allows you to track changes to files and go back to old versions of the file
git - version control software - visit homepage of the software
GitHub - an online hosting service for folders/directories that are version controlled by git - GitHub homepage
Repository/repo - folder/directory under version control
Branch - copies of the repository where you can develop something new in a separate safe copy and then merge it back into the main branch
Commit - saving a change in a file or set of files in a repository (snapshot of the files at that time). Has a unique identifier for each commit saved
Markdown - plain text format where you can add formatting to show github/jekyll how to render the finished webpage
HTML - Slightly more complex formatting way for writing formatting for a webpage, can be used in conjunction with markdown as well
README - A file containing information about your project. Used by GitHub as a landing page for your repository, usually written in Markdown (file extension .md)
CSS - styling instructions to the browser, telling it how to display the structured content described by the HTML of a page
```

**Comment by JulianKarlBauer** [comment]
Additional candidates for glossary entries:
- YAML
- [DRY-principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

**Comment by baileythegreen** [comment]
DRY principle has been added, and YAML has been an entry in Glosario for a while now.

**Comment by sstevens2** [comment]
I did add YAML from glossario into my PR for this lesson's glossery after Julian's suggestion.  I'll go ahead and add DRY principle and README now those have both been merged into glossario too.
