### ISSUE TITLE
Referring to reference-style links which were not explained 

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/jekyll-pages-novice#147]
On "Reusing block of content" episode we refer to reference-style links which we used to cover in Markdown episode:
> "In the Authoring with Markdown section, we learned about writing reference-style links in Markdown, e.g. [link text][link-target] in the body of the file with a corresponding ..."

We need to either explain there reference-style links in the previous episode or remove this section.

I vote for the former - find this very useful.

**Comment by unode** [comment]
A simple example could be using the same email in two (or more) locations in the same document and using a reference-style link while mentioning the [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

**Comment by tobyhodges** [comment]
The way this lesson has developed, this doesn't fit naturally anywhere. Could add it as a _DRY_ callout at the end of the Markdown episode?
