### ISSUE TITLE
Demonstrate how things go wrong

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/jekyll-pages-novice#153]
It would be good to include an example and discussion of what things look like when they go wrong e.g. when trying to use a variable that doesn't exist, in a page and from the site config. I _think_ this will produce two different error outcomes (blank space vs email notification), but need to check that.

**Comment by sstevens2** [comment]
@tobyhodges  I added a page variable `{{ page.variabletest }}` and then a global variable `{{ site.variabletest }}` to `index.md` and both gave me where it left it blank but still re-rendered.  Were there any other conditions I should try to see if I can get the email error?

**Comment by tobyhodges** [comment]
ok, thanks for checking. how about misformatting the YAML in the front matter of a page, and in `_config.yml`?

**Comment by tobyhodges** [comment]
closed by #185
