### ISSUE TITLE
Exercise: adjusting site config

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/jekyll-pages-novice#16]
in `05-starting-jekyll.md`:

need an exercise to test understanding of how site config works from, `_config.yml`. This exercise (or another, separate one) should also include working with global variables (i.e. `site.variable_name` where `variable_name` was set in `_config.yml`).

**Comment by sstevens2** [comment]
Think this is closed by the merging of #27 but @tobyhodges feel free to reopen if not.
