### ISSUE TITLE
Should we add code blocks into the markdown section

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/jekyll-pages-novice#161]
In the new Markdown exercise, we don't ask them to write any code blocks. Was that deliberate (given that they won't need to use it for the rest of the lesson)? Or should we add that in too (given that many of them might want to know how to do this in future)?

From [2020-11-25 pilot workshop](https://codimd.carpentries.org/KyHEeesgS7mXKjwwvmHcrw)

**Comment by tobyhodges** [comment]
Discussed in the 2021-01-12 development sprint. Conclusion: add a callout linking to the Extra page with a more comprehensive overview of Markdown, with specific reference to code blocks.
