### ISSUE TITLE
Callout discussing options for allowing comments on a static blog

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/jekyll-pages-novice#179]
[See this Twitter thread for context](https://twitter.com/StephanJanosch/status/1356215591682650113). It is indeed the case that many folks would imagine comment threads being included on a blog, but Jekyll/GitHub Pages can't support this natively. I propose to add a callout box discussing the options (e.g. Disqus, inviting discussion elsewhere, etc) and the considerations that come with each option. Such a callout should probably live in the Introduction, alongside the discussion of when a static site generator is the appropriate tool for the job.

**Comment by bkamapantula** [comment]
hi @tobyhodges, curious if you're open to suggestions here please?

I tried to configure comments for my github pages website and can share some inputs.

**Comment by tobyhodges** [comment]
Hi @bkamapantula of course! I'd be interested to hear your perspective.

**Comment by bkamapantula** [comment]
thanks @tobyhodges. Do let me know if this content is appropriate or if you were looking for something else.

for my personal blog, I wanted to include comments section and reviewed different options. In each option, I link the website along with the demo. To view the embedded comments section in Demo, scroll to the bottom of the page.

1. Disqus. Disqus website offers [instructions](https://disqus.com/admin/install/platforms/jekyll/) on how to enable comments for Jekyll platform (used for GitHub pages). [Demo](https://erresen.github.io/jekyll/disqus/2016/08/26/getting-comments-working-jekyll-disqus.html). Although if you're privacy inclined the likes of Privacy Badger blocks Disqus widget and might want alternatives.
2. That led me to try [Staticman](https://staticman.net/). This setup is tedious, I couldn't get it to work in the end (I haven't setup any other method yet). [Demo](https://travisdowns.github.io/blog/2020/02/05/now-with-comments.html).
3. [Just Comments](https://just-comments.com/) seems to be another option. [Demo](https://60devs.com/adding-comments-to-your-jekyll-blog.html).
4. [fastpages](https://github.com/fastai/fastpages) is the most recent addition to enable comments via GitHub comments (uses [Utterances](https://utteranc.es/)). fastpages comes with lots of options and is used by several researchers. [Demo](https://fastpages.fast.ai/fastpages/jupyter/2020/02/21/introducing-fastpages.html).

From the comments section implementation standpoint, Disqus looks most simple followed by Just Comments and Staticman.

Fastpages is much more than enabling a comments section. It's a blog template that uses Jekyll as a base, improves on Jekyll experience and offers additional features. For researchers this may be the option to go.

Happy to format this in a different structure if required.

**Comment by tobyhodges** [comment]
This is super helpful, @bkamapantula, thank you. Would you be willing to create a Pull Request to add this information in [a callout box](https://carpentries.github.io/lesson-example/04-formatting/index.html#special-blockquotes) at the end of the _Loops and Collections_ episode?

**Comment by bkamapantula** [comment]
sure @tobyhodges, happy to do that.

just to be sure, I need to edit [04-formatting.md file](https://github.com/carpentries/lesson-example/blob/gh-pages/_episodes/04-formatting.md), right?

also, I couldn't find the text "Loops and Collections" in the mentioned link... (for the placement) but I will add the callout before the Key Points section renders at the end. Hope I understood that correctly.

**Comment by tobyhodges** [comment]
Sorry for the confusion. I linked to https://carpentries.github.io/lesson-example/04-formatting/index.html#special-blockquotes as that page describes how to add a callout box to a lesson page. The source file for the _Loops and Collections_ episode is https://github.com/carpentries-incubator/jekyll-pages-novice/blob/gh-pages/_episodes/arrays.md

**Comment by bkamapantula** [comment]
thanks Toby, noted. Will send a PR soon.

**Comment by tobyhodges** [comment]
Hey @bkamapantula we have another trial run of this lesson coming up next week and it would be great to have this content included before then. Do you expect to be able to submit the PR soon? We would love to have your contribution 🙂

**Comment by bkamapantula** [comment]
Noted @tobyhodges, will do it by then!

**Comment by bkamapantula** [comment]
hi @tobyhodges, here's the PR: https://github.com/carpentries-incubator/jekyll-pages-novice/pull/194

Please review and let me know if anything is missing, will update.
