### ISSUE TITLE
Split up 05-starting-jekyll?

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/jekyll-pages-novice#18]
The Starting with Jekyll episode is probably going to be too long. What's the best point to split it? Perhaps put _includes_ material into its own episode?

**Comment by sstevens2** [comment]
I think it would be good to split it.  I prefer more episodes to less as it is easier to remix as needed then.  I think at includes would be a good split.

**Comment by unode** [comment]
Agree.

**Comment by tobyhodges** [comment]
addressed in f7d57c4f0a9db5ba401151dbf15e481c3915591d
