### ISSUE TITLE
Expand the Jekyll Themes Extra

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/jekyll-pages-novice#189]
The Extras page about Jekyll Themes needs to be expanded. This relates to the discussion of motivating examples (#127) but we definitely need some advice on finding and choosing a theme, some more discussion of licenses and attribution, and the built-in themes offered by GitHub.

**Comment by sstevens2** [comment]
Closing due to changes in PR #237.  Although this does mention licenses and attribution, and built in themes which aren't currently covered in the theme example.  Added a comment that we include these in #270.  Happy to re-open if folks feel this is still needed.
