### ISSUE TITLE
Differences between GitHub Pages and local Jekyll

### ISSUE THREAD

**Issue by unode** [carpentries-incubator/jekyll-pages-novice#197]
This seems to differ from my local Jekyll installation and the one running on GitHub and only becomes visible after [the layout inheritance section](https://carpentries-incubator.github.io/jekyll-pages-novice/layouts/#layout-inheritance) where we tell readers to use `_layouts/default.html` in `_layouts/page.html`.
Adding `title: Sometitle` to the front matter of `page.html` or `index.md` and `about.md` solves the issue.
Seems like `{{ page.title }}` gets replaced with the literal `{{ site.title }}` that was introduced in [the starting jekyll](https://carpentries-incubator.github.io/jekyll-pages-novice/starting-jekyll/) in the GitHub version. The index file has`# {{ site.title }}` as header.
The HTML generated for each of the versions is identical except the the literal `{{ site.title }}` in `h1` and `title` tags on GitHub.

Do we want to remove `{{ site.title }}` altogether and use only `{{ site.description }}` as an example in the starting jekyll lesson?

Code and screenshots below.

-----

`index.md`:
```
---
lesson-example: "https://carpentries.github.io/lesson-example/"
layout: page
---

# {{ site.title }}

## Description

{{ site.description }}

More details about the project are available from the [About page](about).

See some [examples of our work]({{ page.lesson-example }}).

Have any questions about what we do? [We'd love to hear from you!](mailto:{{ site.email }})
```

`_config.yml`:
```
title: "Building Websites in GitHub"
description: "This research project develops training materials for reseachers wanting to learn to build project
websites in GitHub with GitHub Pages."
email: "team@carpentries.org"
twitter: "https://twitter.com/thecarpentries"
```

`_layouts/default.html`:
```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{{ page.title }}</title>
  </head>
  <body>
    <h1>{{ page.title }}</h1>
    <section>
      {{ content }}
    </section>
  </body>
</html>
```

`_layouts/page`:
```
---
layout: default
---

{{ content }}
```

## On Github

![Screenshot_2021-03-07 github](https://user-images.githubusercontent.com/122319/110227288-07558880-7ef7-11eb-98e3-f43be52efe4f.png)

## On local

![Screenshot_2021-03-07 Screenshot-local](https://user-images.githubusercontent.com/122319/110227289-0886b580-7ef7-11eb-8dfd-3c0811e528ac.png)

**Comment by unode** [comment]
This turned out to be related to extra plugins and customizations implemented by GitHub pages.
See [custom settings](https://docs.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#configuring-jekyll-in-your-github-pages-site) and [custom plugins](https://docs.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins).
The issue above is actually caused by the [jekyll-titles-from-headings](https://github.com/benbalter/jekyll-titles-from-headings) plugin.

After the last pilot we also realized that this will make it harder to use the materials with a local installation of jekyll (or platforms like gitpod) as well as in GitLab (see #186) where these customizations do not exist.

Two possibilities were discussed:
* Keep everything as-is but include a section explaining that GitHub has such customizations (would still be a problem if we want to include GitLab)
* Use a [GitHub Action](https://docs.github.com/en/actions) instead of the default GitHub Pages pipeline. Using GitHub actions is also mentioned in [Jekyll's documentation](https://jekyllrb.com/docs/continuous-integration/github-actions/) as having some advantages (would also make it easier to keep in sync with GitLab).

The last option seems the most promising but we would have to pick one of the following:
* Provide a template repository with the GitHub Actions configuration ready to go (GitLab would be an issue again).
* Add an early lesson on how to setup GitHub Actions (easier to keep in sync with GitLab, extra hassle for learners)

Thoughts?

**Comment by sstevens2** [comment]
Need to switch from using `{{ site.title }}` as the first level header on index in the starting with jekyll lesson.  And then check to subsequent episodes to make sure that we use page titles or have a first level header that would work as a page title.

These aren't difficult changes to make but will need to be checked carefully for downstream effects.
