### ISSUE TITLE
Make banner image smaller/lower res

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/jekyll-pages-novice#202]
Love to hear other thoughts on this.  In the recent SSI pilot workshop it felt like this banner always took a while to load.  Maybe we could make the file smaller or lower resolution?

**Comment by unode** [comment]
It's great to have a slow internet every once in a while to notice accessibility issues. :+1: on lowering the resolution a bit.
Alternative is to remove the background gradient which should drastically reduce filesize.

**Comment by tobyhodges** [comment]
Both of these options sound good. I will self-assign this one, and come up with something a bit smaller and flatter.

**Comment by unode** [comment]
Lazy attempt - transforming the PNG to use a 25 color index instead of full RGB, no change to dimensions.
![site_banner_index25](https://user-images.githubusercontent.com/122319/110844505-c7e9bc00-82a9-11eb-8f23-c9846713af4d.png)

```
Before  -  After
475.659 - 55.382 bytes
```
