### ISSUE TITLE
Accessibility of images

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/jekyll-pages-novice#206]
Thinking about the accessibility of the images we are using in the lesson, I have two main points to raise:

1. we need to make sure there is some alternative text for every figure and screenshot.
2. I am not convinced we can write alt-text for the screenshots that would be sufficiently descriptive to replace the purpose of the screenshot (i.e. a representation of what the webpage should look like at this stage of the lesson). I am increasingly convinced that it would be better to have a link to the HTML equivalent of the relevant pages at every step through the lesson, so people can refer to that instead if the screenshot is not available to them (e.g. if they are using a screen reader). This is probably better left until our material is more stable, because it is going to be a bit of a maintainability headache to keep these HTML equivalents in sync with the examples in the lesson...

**Comment by anenadic** [comment]
The Carpentries is hiring an accessibility consultant and this address will be addressed and recommendations made. Will close the issue for now but can reopen in the future to re-address it.
