### ISSUE TITLE
Confusing names of layouts

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/jekyll-pages-novice#209]
Learners found names of layout templates confusing, especially page.html layout vs. page term used for 'webpage'. Default layout was not much better.

**Comment by sstevens2** [comment]
I've mixed feelings on this.  I do understand that the names are pretty general which can be confusing, however it is somewhat authentic in that these are common names used for layouts.

**Comment by tobyhodges** [comment]
Conclusion from discussion at the May 2021 sprint was that this should be added as an Instructor Note, to warn that this is a potential point of confusion for learners.

**Comment by anenadic** [comment]
At the same discussion, it was concluded that we should stick to the layout names used conventionally (even though they may be confusing) - as a point will be added to instructor notes to help clarify the issue for learners (as per the above [comment](https://github.com/carpentries-incubator/jekyll-pages-novice/issues/209#issuecomment-839601127)).

**Comment by annefou** [comment]
Add info in instructor notes.

**Comment by anenadic** [comment]
@annefou Have you got the time to look into this issue over the next week or so? I can take this otherwise.
