### ISSUE TITLE
Loops and Collections episode - replace HTML table in team member example

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/jekyll-pages-novice#210]
Team member example does not have to be in HTML with tables - can be simplified to Markdown lists or HTML lists as HTML tables may be confusing to learners. I suggest HTML lists to get them used to HTML syntax but I used Markdown lists in the 3rd pilot.

**Comment by anenadic** [comment]
We could also use Markdown tables and use this website to quickly generate it (as per @tobyhodges's suggestion): https://www.tablesgenerator.com/markdown_tables

**Comment by annefou** [comment]
replace HTML table by list of names.

**Comment by annefou** [comment]
I am happy to work on this issue!

**Comment by anenadic** [comment]
@annefou I think this one may already have been fixed. Also looks like the URL to posts problem we had at the pilot no. 3 where the links to post were not working correctly has been fixed by using the relative_url filter. This may have been @tobyhodges who fixed this already.

**Comment by tobyhodges** [comment]
I fixed #222 in #238 but this issue (#210) is still relevant: lines 125-131 of `arrays.md` show an HTML table of team members, which should be replaced with a list (in HTML or Markdown, based on your preference). The text may also need adjusting elsewhere in the episode to reflect this change.

**Comment by anenadic** [comment]
Closing via #248.
