### ISSUE TITLE
Loops and collections episode: error in _config.yml where we define post collections

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/jekyll-pages-novice#212]
Need to fix where we create the posts collection in _config  We found removing the "-" seemed to help but this needs fixing and testing.

Note that YAML syntax appears valid in YAML LINT tool and also GH does not complain.

**Comment by sstevens2** [comment]
@anenadic I'm not quite finding where this issue is in the lesson.  I don't see where in the lesson we used a "-" when we created the the posts in `_config`.  I do see a dash when we created it in the `index` file but that seems to work okay in the test site. Can you tell me more?

**Comment by tobyhodges** [comment]
Indeed, this was fixed with e0242aede64d13be24 when the problem was first encountered during the pilot workshop.
