### ISSUE TITLE
Filters episode: navigational menu text is potentially wrong

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/jekyll-pages-novice#214]
Text: (We will actually build a navigational menu like this in the final section.) - is this true?

**Comment by tobyhodges** [comment]
This statement is true, to some approximation: the final section, [Looping Over a Collection](https://carpentries-incubator.github.io/jekyll-pages-novice/arrays/index.html#looping-over-a-collection), shows how to construct a linked list of blog posts. It is quite basic, but does not require a great leap from that to building a navigation menu.
