### ISSUE TITLE
Teach collections, loops, etc?

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/jekyll-pages-novice#22]
Would it be a good idea to cover collections, for loops, conditionals, and other Liquid things?

**Comment by sstevens2** [comment]
I'd put this as an "intermediate" topic.  I've functionally used gh-pages for years and don't deal with these much.

**Comment by sstevens2** [comment]
Maybe an optional lesson?

**Comment by tobyhodges** [comment]
Yes, if we want to keep the time for the lesson to ~3hrs I don't think there's room for more (core) episodes.

**Comment by anenadic** [comment]
Perhaps mention Liquid as a scripting language (and a reference for further reading) in a callout to let people know there are more advanced options. Probably in 05-starting-jekyll episode.

**Comment by tobyhodges** [comment]
there is a plan to address this in #81 so I'm inclined to close this issue now. unless we're well ahead of schedule in prep for the first trial run of the lesson, I would suggest leaving that issue unaddressed while we focus on more immediate concerns.
