### ISSUE TITLE
Create a template repository for preview of both repo status and Jekyll output

### ISSUE THREAD

**Issue by unode** [carpentries-incubator/jekyll-pages-novice#225]
This was an idea discussed with @sstevens2 in today's sprint. Something to consider for the future.

The gist would be to have a repository with progress at all stages of the lesson that we could link to, including sll intermediate rendered versions of Jekyll.

We could in principle use a GitHub action to build every commit in the history of a repository into a subfolder of the GitHub Pages address. We could then have an index with the commit message and links to all the intermediate versions.

Some possibly useful links:
* https://github.com/BryanSchuetz/jekyll-deploy-gh-pages - build jekyll websites with a custom action
* https://github.com/sdras/awesome-actions

**Comment by anenadic** [comment]
Potentially a maintenance hell  - would be a nice thing to have once the lesson is stable. Being able to render the example website at different points would be really nice but may be too difficult/too much work. Won't fix.
