### ISSUE TITLE
Wrap-up - Use an existing theme and create an exercise to modify/add something to it

### ISSUE THREAD

**Issue by unode** [carpentries-incubator/jekyll-pages-novice#233]
To conclude the materials, we would like to show how to use an existing theme that includes the concepts taught.
We can perhaps design a couple of exercises that add content or modify some part of said theme.

For this we need a theme that has an adequate level of complexity. The ideal theme should have:

- A compatible license (MIT, BSD, ...)
- Some variables in `_config.yml`.
- HTML & CSS
- Includes
- Layouts & inheritance
- Collections / Posts
- (optional) Some assets
- (hopefully) Pleasant aesthetics

and doesn't include:

- Too many other collections (e.g. `_data`)
- Sass
- Ruby plugins

We should probably also fork it to ensure it doesn't change in unforeseen ways.

Candidates:
1. https://github.com/themefisher/kross-jekyll - [preview](https://demo.themefisher.com/kross/)
2. https://github.com/wowthemesnet/mundana-theme-jekyll - [preview](https://wowthemesnet.github.io/mundana-theme-jekyll/)
3. https://github.com/brianmaierjr/uni - [preview](http://brianmaierjr.com/uni)

Interesting finds:
- https://github.com/epidrome/cover-card - uses branches with different roles - website on `gh-pages`, template on `main`.

**Comment by sstevens2** [comment]
Decided on option 2 after discussion

**Comment by anenadic** [comment]
In progress: @sstevens2 is working on a [PR](https://github.com/carpentries-incubator/jekyll-pages-novice/pull/237).

**Comment by sstevens2** [comment]
Closing since PR #237 is merged
