### ISSUE TITLE
Fix FIXMEs in 'Filters' and 'Loops and 'Collections' episodes

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/jekyll-pages-novice#244]
A few FIXMEs related to missing screenshots.

**Comment by anenadic** [comment]
Screenshots for 'Filters' episode fixed via #243.

**Comment by tobyhodges** [comment]
The two remaining FIXMEs are both missing screenshots, both in `arrays.md`. So I am closing this in favour of #107
