### ISSUE TITLE
State that the github commit message is best practice

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/jekyll-pages-novice#262]
Suggested by @EKaroune

**Comment by anenadic** [comment]
Writing a more elaborate commit message is best practice for commit messages rather than leaving it to default "updated ..." , Could be a nice callout.

**Comment by sstevens2** [comment]
I'll add a bit more text to the "Writing a Commit Message" callout in the Markdown episode on Feb 28th.

**Comment by sstevens2** [comment]
Writing text here before putting in the PR as I'll be doing the PR as a demo for the Midwest Carpentries Community.
> A commit message is a short, descriptive, and specific comment that will help us remember later on what we did and why.
> When editing in the Github interface, it will suggest a vague message about which file you've updated or added.
> It is best practice to change this message to a short but more informative message about what in the file has changed.
> This more descriptive message will make it much easier if future you needs to go looking through the history
> for which commit made a specific change.
> You find more about writing commit message in [this section](https://swcarpentry.github.io/git-novice/04-changes/index.html) of the Git-novice lesson.

**Comment by tobyhodges** [comment]
closed by #275
