### ISSUE TITLE
Error in Page Layouts episode

### ISSUE THREAD

**Issue by agully1** [carpentries-incubator/jekyll-pages-novice#264]
There appears to be an issue in the [Page Layouts](https://carpentries-incubator.github.io/jekyll-pages-novice/layouts/index.html) episode. In the Layouts Inheritance section, after the first (HTML) code block, there is what should be another code block but the parts which should be in plain text and the parts which should be in code blocks are switched.

**Comment by unode** [comment]
Hi @agully1 thanks a lot for your bug report.
Can you confirm that the issue is indeed fixed?

**Comment by agully1** [comment]
Yes that's fixed now. Thanks!
