### ISSUE TITLE
Broken links in Page Layouts episode

### ISSUE THREAD

**Issue by agully1** [carpentries-incubator/jekyll-pages-novice#265]
In the [Page Layouts](https://carpentries-incubator.github.io/jekyll-pages-novice/layouts/index.html) episode there are 2 broken links:

- Link text "the introduction" in the second paragraph of the HTML Structure, Metadata and a Default Layout section
- Link text "we recommended that you include a file of references" in the 'We Can’t Include Link References in the Layout' box at the bottom of the Layout Inheritance section

**Comment by unode** [comment]
Should be fixed now. Thanks for the report!
