### ISSUE TITLE
Some screenshot images are fuzzy

### ISSUE THREAD

**Issue by kerchner** [carpentries-incubator/jekyll-pages-novice#274]
As an example, the first screenshot on https://carpentries-incubator.github.io/jekyll-pages-novice/github-pages/index.html is fuzzy:

![image](https://user-images.githubusercontent.com/3451175/154579460-e5629526-684b-416e-9988-8774e4a21509.png)

Recommend re-taking the screenshot, but don't resize the image to something too small.  Also recommend checking other images in the lesson.

Great lesson!  Happy to see this.

**Comment by unode** [comment]
This looks like a poor scaling algorithm on the browser when the image has higher resolution than the screen/image where it is being displayed.

Funny enough this affects [Google Chrome but not Firefox](https://stackoverflow.com/a/69156216).

One workaround mentioned is to add `image-rendering: pixelated;` to the `img` CSS.

The other option is to generate thumbnails for all screenshots instead of relying on the browser to re-scale the image.
We can always link the original resolution to open on click.

**Comment by unode** [comment]
Chromium Version 97.0.4692.71 (Official Build) (64-bit)
Without `image-rendering: pixelated;`
![screenshot_2022-02-21_15-04-30_786162206](https://user-images.githubusercontent.com/122319/154970441-280e8689-40c6-437a-9125-808e87b04342.png)

With `image-rendering: pixelated;`
![screenshot_2022-02-21_15-04-18_960034047](https://user-images.githubusercontent.com/122319/154970417-4cd6057e-95d0-4938-88db-d06f38a643c6.png)

Firefox 95.0.2:
Without `image-rendering: pixelated;`
![screenshot_2022-02-21_15-06-59_878937185](https://user-images.githubusercontent.com/122319/154970765-f071ad1c-7232-472c-baae-702cbecdaf67.png)

With `image-rendering: pixelated;`
![screenshot_2022-02-21_15-07-22_466685307](https://user-images.githubusercontent.com/122319/154970804-f0437371-7fc9-41a8-beb5-1d225381f221.png)

Do I get a :+1: to enable this workaround?

Can someone confirm how this looks like in Safari/Edge?

**Comment by tobyhodges** [comment]
Safari 15.2

Without `image-rendering: pixelated;`

<img width="943" alt="Screenshot 2022-02-21 at 15 13 41" src="https://user-images.githubusercontent.com/9694524/154972003-09efc46b-b34e-4f7e-b1cb-564e093849a7.png">

With `image-rendering: pixelated;`

<img width="954" alt="Screenshot 2022-02-21 at 15 14 31" src="https://user-images.githubusercontent.com/9694524/154972041-16c7a20e-cd30-4e99-ae92-c1f8df42bbd0.png">

**Comment by tobyhodges** [comment]
Looks good to me, @unode. Maybe also a change to propose to The Carpentries template?

**Comment by unode** [comment]
Once https://github.com/carpentries/styles/pull/636 is fixed/merged we can merge here and close the issue.

**Comment by unode** [comment]
fixed in 6e35bd3f3cddec87b508c0dd56cb0e849f88612f

**Comment by unode** [comment]
Actually, after enabling the workaround we realized that some of the other images become almost unreadable.
After some discussion we decided to revert this change.

Reverted in f945067cbd3b945e292d0354c20271278f1067c0
