### ISSUE TITLE
Add callout about use & attribution of images online

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/jekyll-pages-novice#278]
In #276, @Sparrow0hawk wrote:

> I spent some time showing how to include images and we talked through using images from an existing URL and if the image was uploaded to the repository, cue some debate about attribution and appropriate use of images from the internet!

A callout should be added to the lesson, with some brief discussion of image use & attribution, to reflect the discussion described here.

**Comment by Sparrow0hawk** [comment]
As re #282 it'd be good to get some extra pointers on good summarises of rules for image reuse online for this callout
