### ISSUE TITLE
Instructions for local builds

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/jekyll-pages-novice#37]
We need an Extras page describing steps required to build and serve a site locally, for Windows (if possible?), MacOS, and Linux.

**Comment by tobyhodges** [comment]
Related to discussion of themes - local previews become more important as website becomes more complex i.e. GitHub preview feature becomes less useful as you add variables, includes, layouts, etc

**Comment by baileythegreen** [comment]
An advanced version of local deployment might also be how to serve the site locally so other devices on the network (phones, tablets) can also access the site. Useful for testing on another device (though Inspect features can also help with this).

**Comment by unode** [comment]
Would referring to [GitHub official documentation on how to build locally](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/testing-your-github-pages-site-locally-with-jekyll) suffice? 
It includes instructions for all 3 major platforms (Windows, Linux, Mac)

**Comment by anenadic** [comment]
Will be addressed via #273.
