### ISSUE TITLE
Finish_02_markdown_challenges

### ISSUE THREAD

**Issue by JulianKarlBauer** [carpentries-incubator/jekyll-pages-novice#4]
Add challenge on links  
[Tobys suggestion](https://github.com/tobyhodges/building-websites-with-jekyll-and-github-or-gitlab/pull/3#discussion_r462919358)

**Comment by tobyhodges** [comment]
I think we're done for Markdown exercises now, so I'll close this. Thanks @JulianKarlBauer!
