### ISSUE TITLE
Add optional page variable reference from other page

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/jekyll-pages-novice#40]
This issue came up in reviewing PR #27 

@unode suggested the addition of an exercise to the starting jekyll episode where we try to refer to a {{ page.(...) }} variable that is defined in another document

**Comment by tobyhodges** [comment]
Suggestion, based on discussion during the Dec 1st sprint: this can be a callout instead of a self-contained exercise, explaining that page variables are local to that page only.
