### ISSUE TITLE
Readme.md to index.md coordination?

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/jekyll-pages-novice#42]
In Review of #28, it came up that maybe we should have them learn Markdown by working in the `README.md` and then changing that to the `index.md` in the beginning of the github episode.  Maybe something to discuss and coordinate at the next sprint?

**Comment by tobyhodges** [comment]
I am a big fan of this idea.

**Comment by tobyhodges** [comment]
We agreed to adopt this approach during [the October 2020 development sprint](https://hackmd.io/8IuM80wURA2uolBgzy_HZg). Do you think we can close this now, @sstevens2?
