### ISSUE TITLE
update reference to previous epsiode in ep3 intro

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/jekyll-pages-novice#48]
Need to make sure Episode 3 says that the GitHub repository was set up at the end of episode 1.

**Comment by JulianKarlBauer** [comment]
After episode `introduction`, a `README.md` exists.
In episode `markdown` we do not ask participants to commit anything, however they may do so.
In episode  `hosting website...` we expect a `README.md` to exist, but as far as a can see there are no requirements on the content.
`README.md` is only mentioned here

![image](https://user-images.githubusercontent.com/55383008/98006186-3a292c00-1df2-11eb-9730-145b3293f177.png)

 and here

![image](https://user-images.githubusercontent.com/55383008/98006104-25e52f00-1df2-11eb-9020-3d5a0e42c0fa.png).

I would like to remove the ambiguity of either copying the `README.md` or starting from scratch.
