### ISSUE TITLE
Improve Screenshot Sizes or Level of Perception

### ISSUE THREAD

**Issue by JulianKarlBauer** [carpentries-incubator/jekyll-pages-novice#51]
Some screenshots and the font sizes they contain are very large compared to the font of the text of the instructions outside the images. 

Adjusting the size of the screenshots may help to increase readability and balance the level of perception of instruction and screenshot. Putting a frame / box around screenshots may be an alternative way of dealing with this.

[Example](https://github.com/carpentries-incubator/building-websites-with-jekyll-and-github-or-gitlab/pull/47#pullrequestreview-503061412)

**Comment by anenadic** [comment]
Might need to use the <img> HTML tag for resizing images, as Markdown options for this are limited.

**Comment by unode** [comment]
Might be better to agree on a resolution and browser zoom level for screenshots all around.
Perhaps worth mentioning in GitHub issue templates or #91 as well.

**Comment by tobyhodges** [comment]
Closing this as I think it is superseded by #107
