### ISSUE TITLE
Update AUTHORS

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/jekyll-pages-novice#58]
Everyone could just add their details?

**Comment by tobyhodges** [comment]
yes please!

**Comment by tobyhodges** [comment]
Please add you details to `AUTHORS` (you can commit directly to `gh-pages` for this) and post a message on this issue when you're done, so we know when to close it.

**Comment by tobyhodges** [comment]
✅

**Comment by anenadic** [comment]
✅

**Comment by anenadic** [comment]
We could also update the list of current maintainers in README with our GH URLs at the same time? Thx to @tobyhodges for assigning to everyone, beat me to it ;-).

**Comment by tobyhodges** [comment]
That sounds like a good plan, @anenadic. BTW has anyone else seen https://github.com/con/tributors ? I think this is another thing I'd like to experiment with on this repository...

**Comment by anenadic** [comment]
> That sounds like a good plan, @anenadic. BTW has anyone else seen https://github.com/con/tributors ? I think this is another thing I'd like to experiment with on this repository...

No, but it sounds really nice! I also like how we use this repo to learn and test new things for material development and general collaboration. Every day is a school day!

**Comment by annefou** [comment]
Yes in CodeRefinery we will use https://con.github.io/tributors/ and https://allcontributors.org in combination to make the contributors more visible. I am really looking forward to it.

**Comment by tobyhodges** [comment]
I discovered it via a tweet from CodeRefinery, @annefou 😄 I think it could be really useful to streamline some of the lesson release process for The Carpentries too!

**Comment by sstevens2** [comment]
Added my info to the authors page and maintainers list in the Readme.

+1 for making recognizing contributions and releasing lessons easier!

**Comment by tobyhodges** [comment]
@elshaek please feel free to submit another pull request, adding your details to the AUTHORS file. (You can leave the the email address out if you'd prefer not to share it there.) And let us know if you'd like to join any of our development sprints in the future!

**Comment by elshaek** [comment]
Hi @tobyhodges I've submitted a PR to add my details to the AUTHORS file :) 

Still taking baby steps and getting myself familiar with open source. Will definitely look out for issues that I can work on in the future!

**Comment by JulianKarlBauer** [comment]
Sorry for the delay, I added the contact details in cd9043662021ec47042b4bda97b7ea8a1bca25b4

**Comment by tobyhodges** [comment]
> Still taking baby steps and getting myself familiar with open source. Will definitely look out for issues that I can work on in the future!

That's great to hear, @elshaek. We'll welcome any contributions you'd like to make, no matter how large or small 🙂

**Comment by sstevens2** [comment]
@unode @annefou You both still need to add yourselves to AUTHORS
