### ISSUE TITLE
plan material for GitHub Pages episode

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/jekyll-pages-novice#6]
We can use this Issue as a place for discussion around the GitHub Pages episode. Next steps might include:

- [x] draft concept map for the episode
- [x] review learning objective(s) & bullet point plan
- [x] design exercise(s) to fit the episode learning objective(s)

**Comment by anenadic** [comment]
Episode outline:

Our narrative revolves around working on a project website where we are adding some info to the index.md page and building a team members page (team.md) and linking the two. We then moving on to using `_config.yml` to configure team members and pull that out via site parameters in team.md page.

- Publishing a repository as a website (heading)
  - Create gh-pages branch (heading)
    - Explain what gh-pages branches are for
    - Create a gh-pages branch in the repo
  - Configure repository as a website (heading)
       - Configure gh-pages branch to be used for serving website (in Settings)
       - Already configured now by defaul, show the settings and where to find the URL
       - Show how to add this URL in the website field of the repo
       - Show the rendered page in GitHub IO, explain this is the HTML version that was converted from the md file with repo name at the top then our md content
       - Explain how URLs are created
       - Convention over configuration: gh-pages branch is used for websites by default, but master or any other branch can be used (callout)
  - Rendering a repository as a website (heading)
      - explain publicly viewable URLs and how they are generated
      - make another change to index.md and see how the website is updated (point out the green tick when GH finishes building the page as feedback to user - as it can take some time)
      - Exercise - create another page called team.md with team members of the project and link to it from the index.md
- Basic website configuration via `_config.yml` (heading)
  - Create `_config.yml` file in the root
  - Add title and email parameters to `_config.yml` and use them from index.md (title is a predefined parameter, email possibly as well) and add some regular parameters (topic and team_members (a dictionary!)) and show how to use them via {{site.title}}
  - Parameters will not render nicely in GH but will in the website/GH IO
  - Explain site wide {{site.paramater}} vs. page wide parameters {{page.paramater}}
- Advanced (TBD): show them how to use team_members dictionary parameter from team.md page

**Comment by anenadic** [comment]
team_members parameter: name, role, start_date - for @sstevens2 and episode 05

**Comment by sstevens2** [comment]
> team_members parameter: name, role, start_date - for @sstevens2 and episode 05

I know I asked for these but now I can't remember what I was planning to do with them 😆 .  Let me know if you remember and it is something that still needs to to be done.
