### ISSUE TITLE
Fix capitalisation on learning objectives in all episodes.

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/jekyll-pages-novice#61]
I still think of learning objectives as finishing the sentence "After following this episode, learners will be able to..." which is why I have the habit of writing them with the first word starting in lowercase. But this doesn't fit with the lesson template and #60 has forced me to face up to the reality that they should start with an uppercase letter to remain consistent with the Questions and Key Points 😑 This needs to be fixed in all episodes.

**Comment by elshaek** [comment]
Hi, I'd like to help with this
