### ISSUE TITLE
Add Markdown/code for the lesson in example website

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/jekyll-pages-novice#66]
As we build the website, we should make sure the Markdown/code works as expected and that we end up with an end product (reference project website). @sstevens2 has created a repo for this purpose: https://github.com/sstevens2/group-website
I needs filling in.

**Comment by tobyhodges** [comment]
What's the best way to do this? To follow the material and create the "finished version" in Sarah's repository? Or to leave the `main` branch of Sarah's repo in this blank initial state and work through the material in forks/imports?

Is it too elaborate to aim for a setup where Sarah's repository has a branch containing the expected "checkpoint" state of the repo at the end of each episode? E.g. a `markdown` branch that contains the completed README.md as it should look at the transition from the Markdown episode to the GHPages episode, a `github-pages` branch containing the files as they should be organised for the beginning of _Starting with Jekyll_, etc? I can imagine it would be useful to be able to quickly refer to these checkpoints when teaching the material.

**Comment by anenadic** [comment]
Not fixing.
