### ISSUE TITLE
Change episode numbers

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/jekyll-pages-novice#67]
At the moment we are missing episode 04 - so once we settle on episodes we should change the numbers to reflect this.

**Comment by tobyhodges** [comment]
I think I'd like to use [manual episode ordering](https://github.com/carpentries/styles/pull/437) here, removing the numbers from the episode titles altogether. That will make it much easier to include and switch in/out an episode on GitLab Pages in the future.

In case someone reads this and wants to have a go at implementing the manual ordering, it's activated by adding a `episode_order` field to `_config.yml` with an array of episode filename slugs afterwards, e.g.

```
episode_order:
    - introduction
    - first_steps
    - running
    - jumping
    - gymnastics
    - olympics
    - conclusion
```

**Comment by anenadic** [comment]
Thank for this @tobyhodges - was not aware how this worked.
