### ISSUE TITLE
Plan material for GitLab pages episode

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/jekyll-pages-novice#7]
We can use this Issue as a place for discussion around the GitLab Pages episode. Next steps might include:

- [ ] draft concept map for the episode
- [ ] review learning objective(s) & bullet point plan
- [ ] design exercise(s) to fit the episode learning objective(s)

**Note: if focusing on GitHub Pages for now, all other episodes should take precedence over this one...**

**Comment by tobyhodges** [comment]
This will be a page in Extras, for now, while we focus on getting the lesson ready to teach with GitHub.

**Comment by unode** [comment]
@tobyhodges and I were discussing possibilities of running the workshop using GitLab. I'm happy to give that a try and add the content bits to make the lesson compatible with GitHub/GitLab.

I was also thinking of using the same "tabbed" views that are used in the software installation instructions.
For example [at the bottom of this setup page](https://swcarpentry.github.io/shell-novice/setup.html).

**Comment by anenadic** [comment]
Revisit this issue at the maintainers meeting in June.

**Comment by unode** [comment]
See #186 for reason to close this
