### ISSUE TITLE
List rendered from 1. instead of 23. in Episode 02 Exercise "Lists, enumerations"

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/jekyll-pages-novice#71]
Also, "4. **without** disturbing the enumeration count." sub-bullet point in the solution needs to be consistent with exercise body.
 
![Screenshot 2020-10-30 at 17 21 55](https://user-images.githubusercontent.com/631719/97737160-8e6f9b80-1ad4-11eb-8da6-01f69558e350.png)

**Comment by JulianKarlBauer** [comment]
Hi Alexksandra,
thank you for pointing at this and sorry for this bulky exercise.
I simplified it a bit:

![image](https://user-images.githubusercontent.com/55383008/97816271-70509980-1c94-11eb-97a3-62f2c69a41a6.png)

- [ ] Do you think I should skip the point of starting lists at indices other than one completely? I am totally fine with that.

- [ ] I would like to make the point about adjusted numbering after deletion of e.g. the fourths item in this example. Or do you think it is too much misleading?

**Comment by anenadic** [comment]
It looks good as far as I am concerned - I think starting a list from any number is useful (Markdown is sometimes too smart and starts the list from the number it wants rather then one we want :-)). I think perhaps this should be pointed out (the fact the Markdown continues the list numbering after items have been removed) as people may be confused as what happened there. Great stuff @JulianKarlBauer - we should merge this.

**Comment by JulianKarlBauer** [comment]
Hey @anenadic,
I am not sure what to do here...
If someone is interested in the numbering, he/she probably will play around with it and discover the renumbering.

Or do you think moving 
> This updated the numbering if individual items are deleted

from within the exercise could be reformulated or elaborated in detail outside of the exercise?

**Comment by tobyhodges** [comment]
How about this? (I think "but" is better than "and" here because it can appear inconsistent that Jekyll respects the number you choose at the start of the list but then doesn't care what numbers you type after that 🙃)

```
2. Enumerations can start at any number but
3. continue to increase in steps of one
5. even if the numbering does not. This updates the rendered numbering to avoid gaps when individual items are deleted.
```

**Comment by JulianKarlBauer** [comment]
See #93
