### ISSUE TITLE
Episode 02, exercise "Links" - code block in the exercise body is redundant 

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/jekyll-pages-novice#72]
Not quite sure but feels like code block in the exercise body is redundant and should only be in the solution body.

![Screenshot 2020-10-30 at 17 34 30](https://user-images.githubusercontent.com/631719/97738566-6f720900-1ad6-11eb-82e9-575fbe4677a4.png)

**Comment by annefou** [comment]
I will look at it!

**Comment by anenadic** [comment]
I did not understand that this was a faded example - apologies. This may be a non-issue in this case or just needs a bit better wording.

**Comment by annefou** [comment]
I still believe we can ask participants to write it from scratch. I mean there is not much to write .
