### ISSUE TITLE
Files overview diagram

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/jekyll-pages-novice#78]
I was wondering if it would be good to have an overview of all the files that compose a website - perhaps at the end of the lesson as a recap.

I did not have the time to draw it but this image captures the idea:
https://razorsite.co/img/bowtie-theme-structure.jpg

**Comment by tobyhodges** [comment]
I think this is a great idea, but non-essential for our first trial run.

**Comment by tobyhodges** [comment]
If we end up introducing some theming into our example repo, and a collection folder or two, this could be a diagram of the intended end result of the lesson itself. For now, we can use this `carpentries-incubator/building-websites-with-jekyll-and-github-or-gitlab/` repository

**Comment by tobyhodges** [comment]
This was fixed in #176
