### ISSUE TITLE
Plan material for Jekyll basics episode

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/jekyll-pages-novice#8]
We can use this Issue as a place for discussion around the Starting with Jekyll episode. Next steps might include:

- [x] draft concept map for the episode
- [x] review learning objective(s) & bullet point plan
- [x] design exercise(s) to fit the episode learning objective(s)

**Comment by sstevens2** [comment]
Since we've split this into two episodes.  I'm wondering if maybe we should rename the episode to something like "working with variables in Jekyll"?

**Comment by sstevens2** [comment]
@unode made a good point in our discussion that has me thinking differently about this lesson.  That this is the point where we actually talk about that you've been using jekyll to perform the magic all along. so maybe we should leave it for now.
