### ISSUE TITLE
Test the materials ahead of Pilot 1 by 9th November

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/jekyll-pages-novice#84]
People involved:
- [ ] Anne
- [ ] Julian
- [x] Renato

Things to do:
- Review episodes from the beginning through the end of the Filters episode (do not worry about the last episode on Loops)
- File issues you discover along the way (think SMART!)
- Check you name off the above list once finished and make a comment on this issue

**Comment by unode** [comment]
Done with reviewing introduction.

See #105 and #106
