### ISSUE TITLE
Plan material for templates episode

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/jekyll-pages-novice#9]
We can use this Issue as a place for discussion around the Page Templates episode. Next steps might include:

- [x] draft concept map for the episode
- [x] review learning objective(s) & bullet point plan
- [x] design exercise(s) to fit the episode learning objective(s)

**Comment by sstevens2** [comment]
I'm wondering if we should cover making your own layouts?  Or if instead we should show some common layouts in popular themes and how to work with them.

I'd like to learn more about layouts but my own usage so far has been more using existing layouts than making my own.

**Comment by tobyhodges** [comment]
In #76 I went with the former approach. That is, creating a layout from scratch. But I agree that the more common usage is to adapt pre-existing layouts and indeed the same point is valid for much of what the lesson material covers, beyond writing Markdown and initialising GitHub Pages. However, the sudden jolt of cognitive load when adopting a pre-made theme is what's put me off up to now. 

I wonder if we should add an applied example at the end of the lesson, where we discuss process of incorporating our example material into a pre-existing, free, open source theme and study a few of the features of that theme and how they work?
